"""add cost_usd to agent_runs

Revision ID: a11b3629c532
Revises: ecb52c328174
Create Date: 2026-04-03 16:53:50.187235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11b3629c532'
down_revision: Union[str, Sequence[str], None] = 'ecb52c328174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###

    # Backfill cost_usd for existing records
    # gpt-5.4:      $2.50 input / $15.00 output per 1M tokens
    # gpt-5.4-mini: $0.75 input / $4.50  output per 1M tokens
    op.execute("""
        UPDATE agent_runs
        SET cost_usd = ROUND(
            CASE model
                WHEN 'gpt-5.4'      THEN (COALESCE(tokens_input,0) * 2.50 + COALESCE(tokens_output,0) * 15.00) / 1000000.0
                WHEN 'gpt-5.4-mini' THEN (COALESCE(tokens_input,0) * 0.75 + COALESCE(tokens_output,0) *  4.50) / 1000000.0
            END, 6)
        WHERE cost_usd IS NULL
          AND model IN ('gpt-5.4', 'gpt-5.4-mini')
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'cost_usd')
    # ### end Alembic commands ###
