"""add intent field to agent_runs

Revision ID: ecb52c328174
Revises: 561d173378c1
Create Date: 2026-04-03 10:12:00.964158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb52c328174'
down_revision: Union[str, Sequence[str], None] = '561d173378c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('intent', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'intent')
    # ### end Alembic commands ###
